[package]
name = "smearor-wrot-process"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[dependencies]
dashmap = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
smearor-wrot-socket = { path = "../smearor-wrot-socket" }
thiserror = { workspace = true }
tracing = { workspace = true }
typed-builder = { workspace = true }
which = { workspace = true }

[lints]
workspace = true
