[book]
title = "smearor-wrot-process-manager Documentation"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
language = "en"
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/smearor/process-manager"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
